# Generated by Django 5.2.1 on 2025-06-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntakeForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the person submitting the form.",
                        max_length=255,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The email address where the user can be contacted.",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Optional phone number provided by the user.",
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The user's message or reason for scheduling a call.",
                        verbose_name="Message",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional: the datetime selected by the user for a scheduled call.",
                        null=True,
                        verbose_name="Scheduled Date and Time",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the form was submitted.",
                        verbose_name="Submitted At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intake Form Submission",
                "verbose_name_plural": "Intake Form Submissions",
                "ordering": ["-submitted_at"],
                "get_latest_by": "submitted_at",
            },
        ),
    ]
